### ISSUE TITLE
React URL-support

### ISSUE THREAD

**Issue by hdjhi** [Martturi/cv_master#70]
React app supports sharing CVs with URL. Server always gives the React-app, and then looks at the URL to get the CV.

- [x] Server always gives react app
- [ ] React reads uid from URL and gets it from server, updates search-field with full name
- [ ] Updates url with new CV number when search-field is used and CV is clicked.

**Comment by mmsavo** [comment]
+ TODO:
[ ] Pass UID read from URL to other components
[ ] Make a 404 page
[ ] Modify URL if user clicks other CV or user.

**Comment by mmsavo** [comment]
* TODO:

- [ ] Remove "cvs" from url 
- [ ] Add for example an "#edit"-tag to url when in editor
