### ISSUE TITLE
UI changes based on review feedback

### ISSUE THREAD

**Issue by Korkkii** [Martturi/cv_master#94]
- [x] Combine Browse and My CVs views
- [ ] Fine tune UI

**Comment by annalonka** [comment]
* Meneekö roskiksesta suoraan roskiin vai tuleeko varmistus
* Ei rename cv vaan pelkkä rename
* skrollaaminen, optimaali, että menis previewssa siihen kohtaan mitä kirjottaa
* Muokkaa edit nappi browse näkymässä cv:n nimen viereen
* Erikseen scrollattavat listat, vaikuttaa html rakenteeseen
* cv:n nimen kohtaan metadataa, esim milloin viimeks muokattu
* My CVs on browse, mutta omat filtteröitynä
    * Ei ollenkaan alkuperäistä myCVs näkymää
    * Browse näkymään joku filtterinappi tms, että vain omat cv:t ja jos haluaa etsiä muiden cv:tä nii ottaa sen pois
    * Ei tarvi ollenkaan create new nappia
    * cv:t järjestyy sen mukaan mikä on viimeks avattu
        * kaikilla on malli cv, jos on ekaa kertaa käyttämässä
    * Ihmisten “ostoskori” ja pystyy tuottamaan yhden cv:n kaikista ihmisistä
* Editorin muokkaus
    * Onko yksi cv, joka sisältää englannin ja suomenkielisen
    * esim tabi vasemmalle mistä pystyy vaihtelemaan kieltä
    * tai tekstibokseille omat tabit mistä pystyy vaihtelemaan englannin ja suomen välillä
    * previewlle toggle onko näkyvillä vai ei
    *( live previewn vois avata toiseen ikkunaan )
* Jos joku lähtee reaktorilta, niin mitä tehdään sen henkilön cv:lle
    * jääkö roikkumaan, piilotetaanko, poistetaanko jne
