### ISSUE TITLE
Browser view button functionality

### ISSUE THREAD

**Issue by Korkkii** [Martturi/cv_master#97]
- [x] Copy button
- [x] Rename button
- [x] Edit button
- [x] Delete button
  - [x] Verification for deletion
  - [x] Discuss with PO what happens when trying to delete last CV
- [x] Export button

**Comment by millaalakuijala** [comment]
Export-button on nyt toiminnallinen myos Browse-nakymassa, mutta vaatii vahan rebaseilua :)
